export interface DatosOrden {
  fila: number;
  idOrden: string;
  numeroOrden: string;
  serie: string;
  modelo: string;
  cliente: string;
  falla: string;
}

export const datosOrdenes: DatosOrden[] = [
  {
    fila: 1,
    idOrden: '#10001',
    numeroOrden: 'ORD-2026001',
    serie: 'S-001',
    modelo: 'iPhone 13',
    cliente: 'Juan Pérez',
    falla: 'No enciende',
  },
  {
    fila: 2,
    idOrden: '#10002',
    numeroOrden: 'ORD-2026002',
    serie: 'S-002',
    modelo: 'Samsung S22',
    cliente: 'Ana Gómez',
    falla: 'Pantalla rota',
  },
  {
    fila: 3,
    idOrden: '#10003',
    numeroOrden: 'ORD-2026003',
    serie: 'S-003',
    modelo: 'Xiaomi 11',
    cliente: 'Carlos Ruiz',
    falla: 'No carga',
  },
  {
    fila: 4,
    idOrden: '#10004',
    numeroOrden: 'ORD-2026004',
    serie: 'S-004',
    modelo: 'Motorola G9',
    cliente: 'Laura Torres',
    falla: 'Batería inflada',
  },
  {
    fila: 5,
    idOrden: '#10005',
    numeroOrden: 'ORD-2026005',
    serie: 'S-005',
    modelo: 'Huawei P40',
    cliente: 'Pedro Díaz',
    falla: 'Cámara borrosa',
  },
  {
    fila: 6,
    idOrden: '#10006',
    numeroOrden: 'ORD-2026006',
    serie: 'S-006',
    modelo: 'iPhone 12',
    cliente: 'Sofía López',
    falla: 'No reconoce SIM',
  },
  {
    fila: 7,
    idOrden: '#10007',
    numeroOrden: 'ORD-2026007',
    serie: 'S-007',
    modelo: 'Samsung A52',
    cliente: 'Miguel Castro',
    falla: 'No carga rápido',
  },
  {
    fila: 8,
    idOrden: '#10008',
    numeroOrden: 'ORD-2026008',
    serie: 'S-008',
    modelo: 'Xiaomi Redmi 10',
    cliente: 'Valeria Ríos',
    falla: 'No vibra',
  },
  {
    fila: 9,
    idOrden: '#10009',
    numeroOrden: 'ORD-2026009',
    serie: 'S-009',
    modelo: 'Motorola E7',
    cliente: 'Andrés Gil',
    falla: 'No suena',
  },
  {
    fila: 10,
    idOrden: '#10010',
    numeroOrden: 'ORD-2026010',
    serie: 'S-010',
    modelo: 'Huawei Y9',
    cliente: 'Patricia Vega',
    falla: 'No carga',
  },
  {
    fila: 11,
    idOrden: '#10011',
    numeroOrden: 'ORD-2026011',
    serie: 'S-011',
    modelo: 'iPhone 11',
    cliente: 'Ricardo León',
    falla: 'No enciende',
  },
  {
    fila: 12,
    idOrden: '#10012',
    numeroOrden: 'ORD-2026012',
    serie: 'S-012',
    modelo: 'Samsung S21',
    cliente: 'Gabriela Mora',
    falla: 'Pantalla negra',
  },
  {
    fila: 13,
    idOrden: '#10013',
    numeroOrden: 'ORD-2026013',
    serie: 'S-013',
    modelo: 'Xiaomi 10T',
    cliente: 'Jorge Peña',
    falla: 'No carga',
  },
  {
    fila: 14,
    idOrden: '#10014',
    numeroOrden: 'ORD-2026014',
    serie: 'S-014',
    modelo: 'Motorola G8',
    cliente: 'Daniela Cruz',
    falla: 'No reconoce huella',
  },
  {
    fila: 15,
    idOrden: '#10015',
    numeroOrden: 'ORD-2026015',
    serie: 'S-015',
    modelo: 'Huawei P30',
    cliente: 'Esteban Soto',
    falla: 'No enciende',
  },
];
